### PR TITLE
Oom issue

### PR DESCRIPTION
**Pull request by jsindt**
Adding an FAQ entry about OOM error, and a Known Issue about OOM caused by bug in OFI MPICH.

### CODE REVIEW

**Review by kevinstratford — COMMENTED** [review]
Is there a reason to use both 'module switch' and 'module swap' in consecutive lines?

**Review by jsindt — COMMENTED** [review]
Good point -- changed one of those to be consistent

**Review by kevinstratford — COMMENTED** [review]
Looks ok.

**Review by kevinstratford — DISMISSED** [review]

**Review by kevinstratford — APPROVED** [review]
FAQ entries ultimately should not reference Archer1, as references
will be anachronistic. OK for now.

**Pull request merged**
