### PR TITLE
CESM2 setup and running instructions

### PR DESCRIPTION
**Pull request by cemac-ccs**
Adds setup and running instructions to the 'other-software' section for CESM 2.1.3, the community earth system model.

### CODE REVIEW

**Comment by cemac-ccs** [comment]
Edits are complete, ready for review of updates and for PR to be changed from being 'draft' status

**Review by mbareford — COMMENTED** [review]
**cesm213_run.md**
1. In the "Preparing a case" section should the example case name start with "b.e213" rather than "b.e20" to indicate that cesm/2.1.3 is being used?
2. In the "Run the case" section, perhaps mention that the "cpl.log" file is to be found within a gz archive file called something like "cpl.log.1576731.220518-143111.gz", which is itself stored off $CESM_ROOT/archive?

**Comment by mbareford** [comment]
I've managed to run two of the four test cases detailed on the "cesm_further_examples.md" page, Atmosphere-only and Coupled Ocean. Both runs ran for 5 simulation days.

The Slab Ocean case fails due to an attempt to open a directory as if it were a file. I think this stems from the fact that within "./Buildconf/cice.input_data_list", grid_file and kmt_file are both set to "$CESM_ROOT/cesm_inputdata/".

The WACCM-X case fails with this error.
"ERROR: edyn_mpi: nmaglons per task"
">>> mp_distribute_mag: each task must carry at least 4 longitudes. task=   0 nmaglons=   3"

**Comment by mbareford** [comment]
I can now run all four test cases (for 5 simulation days) if I you use my n02 project account.
If using a different project account, such as z19 (EPCC staff), that waccm-x test repeatedly fails with errors like the following.

```
Wed Jun  8 09:46:49 2022: [PE_192]:inet_listen_socket_setup:inet_setup_listen_socket: bind failed port 26750 listen_sock = 7 Address already in use
Wed Jun  8 09:46:49 2022: [PE_192]:_pmi_inet_listen_socket_setup:socket setup failed
Wed Jun  8 09:46:49 2022: [PE_192]:_pmi_init:_pmi_inet_listen_socket_setup (full) returned -1
```
So perhaps it needs to be made clear that user must launch jobs from n02 account.
I notice that one of the commands on the setup page has ``/work/n03/n03/$USER/CESM213`` so perhaps this should be changed.

**Comment by mbareford** [comment]
To get the Slab Ocean (ETEST) case to work I needed to alter the instructions following DavidC's advice.

```
${CIMEROOT}/scripts/create_newcase --case [case name] --compset ETEST --res f09_g17 --walltime [enough time] --project [project code] --run-unsupported
cd [case directory]
./xmlchange NTASKS=1024,NTASKS_ESP=1
./xmlchange NTHRDS=2
./xmlchange ROOTPE_ICE=0,ROOTPE_OCN=0
[Any other changes e.g. run length or resubmissions]
./case.setup
./case.build
./case.submit
```

What's changed here is the resolution and the setting of ROOTPE_ICE and ROOTPE_OCN.

**Comment by mbareford** [comment]
To get the WACCM-X (FXHIST) case to work I needed to reduce the NTASKS setting (again following DavidC's advice) from 1024 to 512.

**Comment by mbareford** [comment]
One last thing I noticed is that when I ran ``source ./.env_mach_specific.sh`` from the building cprnc instructions I saw this message.

`The following dependent module(s) are not currently loaded: cray-hdf5-parallel (required by: CESM2/2.1.3), cray-netcdf-hdf5parallel (required by: CESM2/2.1.3), cray-parallel-netcdf (required by: CESM2/2.1.3)`

This is probably because the configure command has ``mpi-serial``. Anyway, I simply ignored this message and all was well. I don't remember this from before so perhaps a note in the docs is needed.

**Comment by cemac-ccs** [comment]
Suggested changes have been made in light of MB recommendations.

**Review by mbareford — APPROVED** [review]
That looks fine!

**Pull request merged**
