### PR TITLE
added instructions for mpi and omp applications with MITgcm

### PR DESCRIPTION
**Pull request by fraserwg**
Partly solves issue #438

### CODE REVIEW

**Comment by aturner-epcc** [comment]
@DanJonesOcean Are you happy with this addition to the docs?

**Comment by DanJonesOcean** [comment]
Hi @aturner-epcc. This looks okay to me, although I haven't tested it. 

I'm guessing that you've tested it, @fraserwg? If so and it works, then yes I'm happy with this addition. Thanks very much for the contribution, @fraserwg.

**Comment by fraserwg** [comment]
I've used this to produce hybrid omp mpi executables which (successfully) run, but haven't done any "formal" testing with it. Happy to try it on some of the verification experiments if needed?

**Review by DanJonesOcean — APPROVED** [review]

**Review by DanJonesOcean — APPROVED** [review]

**Comment by DanJonesOcean** [comment]
Hi @fraserwg. If you're happy that it works, then I don't think we need any formal testing. 

Thanks for doing this! It's a nice addition to the documentation. 

@aturner-epcc, I approved the changes, but I think someone with write access has to formally approve it, yeah?

**Comment by aturner-epcc** [comment]
Yes, approval is needed by admins on the repo. I'll do that now. Thanks @fraserwg @DanJonesOcean

**Review by aturner-epcc — APPROVED** [review]
LGTM

**Pull request merged**
