### PR TITLE
Moved Singularity CMake issue to resolved list.

### PR DESCRIPTION
**Pull request by mbareford**

### CODE REVIEW

**Comment by aturner-epcc** [comment]
@mbareford Just a quick check. Does this now work with the default programming environment (20.10)?

**Comment by mbareford** [comment]
Do you mean cpe/21.03?
I would need to check: this would involve rebuilding the containerised GROMACS against the new Cray mpich library.
The compilation itself is done by instances of cmake and gcc10 installed within the container, so it's just the new
libraries introduced by the PE 21.03 that might change things.
If there is a problem could it be raised as a new open issue and so this pull request could go through?

**Comment by aturner-epcc** [comment]
OK, I think you have answered my question. I do not care about CPE 21.03 at this stage.

**Review by aturner-epcc — APPROVED** [review]
Looks fine

**Pull request merged**
