### PR TITLE
Add test-only option to the scheduler section

### LINKED ISSUE #350: Document use of Slurm `--test-only` option
`--test-only` allows you to see when your job is likely to run:

```
$ sbatch --test-only -p standard --qos standard --nodes=1 --time=10:00 --account=z02 xthi.sh
sbatch: Job 639625 to start at 2021-11-13T04:47:02 using 256 processors on nodes nid001294 in partition standard
```

### PR DESCRIPTION
**Pull request by juanfrh**
Fixes #350

### CODE REVIEW

**Comment by kevinstratford** [comment]
You might want a rider that any estimated start time from might need to be treated with some caution...

**Comment by aturner-epcc** [comment]
I also wonder if this deserves a bit more prominence than just a hint. Maybe we could make a subsection with a title such as "--test-only: Checking scripts and estimating start time"

I agree with @kevinstratford that we should add a note of caution with the estimated start time.

**Review by welucas2 — COMMENTED** [review]
This information should be very useful to users, but I think the comments made by @kevinstratford and @aturner-epcc are sound: we should be cautious and state that the estimated start time is in no way guaranteed. I have another question: how does this fit in alongside the current section on 'checkScript job submission script validation tool'? I imagine both tools are useful. Would it be better to place this new information next to that section?

**Comment by aturner-epcc** [comment]
Yes, putting it next to that section would be good. I also had the idea of making checkScript run the script with --test-only and then it could do additional validation and give an estimated start time. I will look at doing that.

**Comment by juanfrh** [comment]
Thanks for the feedback, @kevinstratford, @aturner-epcc, and @welucas2. The text has been written in a section alongside checkScript rather than using the hint box. A rider has been added to clarify that the start time may differ.

**Review by aturner-epcc — APPROVED** [review]
LGTM

**Pull request merged**
