### PR TITLE
added mpi envionment section

### PR DESCRIPTION
**Pull request by JPRichings**
Updates in line with recommendations in issue #448 "Add information on initialising MPI connections in OFI to Tuning section".

Please let me know of any changes needed.

### CODE REVIEW

**Comment by mbareford** [comment]
Just a few typos.
1. "avalible"
2. "variabels"
3. "benefical"
4. "automaticaly"
For consistency, I would surround the two export commands with ```, as is done for the "man_info" command.
Also, replace "Archer2" with "ARCHER2" as the all caps form is already used on the tuning page.

**Comment by JPRichings** [comment]
Updated version with suggested changes now available.

**Comment by mbareford** [comment]
LGTM

**Comment by kevinstratford** [comment]
Please check closely. E.g.,
```
kevin@ln01:> man intro_mpi
```
not `info_mpi`.

**Comment by aturner-epcc** [comment]
> Please check closely. E.g.,
> 
> ```
> kevin@ln01:> man intro_mpi
> ```
> 
> not `info_mpi`.

Fixed

**Review by aturner-epcc — APPROVED** [review]
Looks good - thanks all

**Pull request merged**
