### PR TITLE
Adds initial RDFaaS docs

### PR DESCRIPTION
**Pull request by aturner-epcc**
This should not be merged until it is confirmed that the RDFaaS file system is available to users.

### CODE REVIEW

**Review by markgbeckett — COMMENTED** [review]
I think this is good for now, though it may be confusing for people who have not previously used ARCHER. It might be worth putting a note next to the entry for RDFaaS when it is first mentioned (in the list of file systems) to say that it is currently only of use to people moving from ARCHER to ARCHER2. That will at least put their mind to rest.

**Comment by aturner-epcc** [comment]
@markgbeckett Thanks, I will add that in.

**Comment by aturner-epcc** [comment]
@markgbeckett Added the requested note. Can you check this is what you meant?

**Review by markgbeckett — APPROVED** [review]
Hi Andy, Thanks for updating. These changes look complete and correct, from my perspective. Best wishes, George.

**Pull request merged**
