### PR TITLE
The qos for `short` is `shortqos`, not just `short`

### PR DESCRIPTION
**Pull request by wood-chris**

### CODE REVIEW

**Comment by aturner-epcc** [comment]
@wood-chris The QoS is called ``short``. I have just submitted using ``--qos=short`` and it works. You can also see this on the system:

```
> sacctmgr show qos short
      Name   Priority  GraceTime    Preempt   PreemptExemptTime PreemptMode                                    Flags UsageThres UsageFactor       GrpTRES   GrpTRESMins GrpTRESRunMin GrpJobs GrpSubmit     GrpWall       MaxTRES MaxTRESPerNode   MaxTRESMins     MaxWall     MaxTRESPU MaxJobsPU MaxSubmitPU     MaxTRESPA MaxJobsPA MaxSubmitPA       MinTRES 
---------- ---------- ---------- ---------- ------------------- ----------- ---------------------------------------- ---------- ----------- ------------- ------------- ------------- ------- --------- ----------- ------------- -------------- ------------- ----------- ------------- --------- ----------- ------------- --------- ----------- ------------- 
     short        500   00:00:00                                    cluster          DenyOnLimit,RequiresReservation               1.000000                                                                               node=32                                 00:20:00       node=32         4          16                             
```

Can I close this PR without merging?

**Comment by wood-chris** [comment]
@aturner-epcc argh, sorrry! I'd got confused with the `--reservation`, which I think needs to be set as

```
#SBATCH --reservation=shortqos
```

but I couldn't see this in the docs

**Comment by aturner-epcc** [comment]
The `--reservation=shortqos` was needed on the 4-cab but is not needed on the full system

**Comment by wood-chris** [comment]
I've just got this error when I didn't specify it:

```
sbatch rs_mpich_bind_clean 
sbatch: error: 0: Job rejected: Please use the reservation QoS for this reservation.
sbatch: error: Batch job submission failed: Unspecified error
```

**Comment by aturner-epcc** [comment]
Please submit a query to the Service Desk

**Pull request closed without merging**
